# Generated by Django 5.2.7 on 2025-10-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_title_post_anonymous_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
