# Generated by Django 5.2.7 on 2025-10-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_story_story_content_remove_story_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distress_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
