# Generated by Django 5.2.7 on 2025-10-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_created_at_distressalert_detected_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distressalert',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='distressalert',
            name='distress_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
